services:
  api: 
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

  alembic:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "alembic upgrade head"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=books_db
      - DATABASE_HOSTNAME=postgres
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d books_db"]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/

    
volumes:
  postgres-db:
